### ISSUE TITLE
RabbitListener processAmqpListener no such bean error

### ISSUE THREAD

**Issue by caozhiyuan** [freenowtech/spring-multirabbit#18] opened 2020-02-24 06:22 UTC
if none producer (not autowired ConnectionFactoryContextWrapper ), only consumer will raise error (RabbitListener processAmqpListener no such bean) , please before  super.processAmqpListener get ConnectionFactory bean.

**Comment by rwanderc** [comment] 2020-02-25 13:57
@caozhiyuan could you give more details what is the problem?
I didn't understand which kind of error the consumer will raise, or which bean is supposedly missing. Having only `RabbitListener` should be a total fine use case.
An example repository showcasing the error would also help clearing things up.

**Comment by caozhiyuan** [comment] 2020-02-26 00:26
at this demo ( https://github.com/freenowtech/spring-multirabbit/tree/release/2.2/spring-multirabbit-examples/spring-multirabbit-example-java/src/main/java/com/mytaxi/spring/multirabbit/example ) remove SomeController.java and run app . @rwanderc

**Comment by rwanderc** [comment] 2020-02-26 08:38
thanks @caozhiyuan, I will look into it and update the thread

**Comment by rwanderc** [comment] 2020-08-07 07:40
Fixed versions released 2.2.1 and 2.1.5

**Comment by rwanderc** [comment] 2020-08-07 12:18
Fix didn't work. Investigating.

**Comment by rwanderc** [comment] 2021-02-08 07:50
@caozhiyuan, the issue was fixed in the versions v.2.1.6 and v2.2.2.

**Closed by rwanderc** 2021-02-08 07:50 UTC
Labels: bug, v2.1.6, v2.2.2

**Comment by a1392136** [comment] 2023-02-16 07:42
I have the same problem
* spring-boot-starter-amqp:2.7.0
* spring-multirabbit:2.7.0

**error log:**
```
Application failed to start due to an exception org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'idm-admin' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:872) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1344) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:309) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.amqp.rabbit.annotation.RabbitListenerAnnotationBeanPostProcessor.resolveAdmin(RabbitListenerAnnotationBeanPostProcessor.java:510) ~[spring-rabbit-2.4.5.jar:2.4.5]
	at org.springframework.amqp.rabbit.annotation.RabbitListenerAnnotationBeanPostProcessor.processListener(RabbitListenerAnnotationBeanPostProcessor.java:459) ~[spring-rabbit-2.4.5.jar:2.4.5]
	at org.springframework.amqp.rabbit.annotation.RabbitListenerAnnotationBeanPostProcessor.processAmqpListener(RabbitListenerAnnotationBeanPostProcessor.java:375) ~[spring-rabbit-2.4.5.jar:2.4.5]
	at org.springframework.amqp.rabbit.annotation.MultiRabbitListenerAnnotationBeanPostProcessor.processAmqpListener(MultiRabbitListenerAnnotationBeanPostProcessor.java:48) ~[spring-rabbit-2.4.5.jar:2.4.5]
	at org.springframework.amqp.rabbit.annotation.RabbitListenerAnnotationBeanPostProcessor.postProcessAfterInitialization(RabbitListenerAnnotationBeanPostProcessor.java:305) ~[spring-rabbit-2.4.5.jar:2.4.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:455) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1808) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.20.jar:5.3.20]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.0.jar:2.7.0]
	at com.ziyun.iot.event.admin.AdminApplication.main(AdminApplication.java:18) ~[classes/:?]
```

I added the @ DependsOn (MultiRabbitConstants CONNECTION_FACTORY_BEAN_NAME) after everything is ok.
I guess because MultiRabbitListenerAnnotationBeanPostProcessor than MultiRabbitAutoConfiguration injection caused by the spring container first?

MultiRabbitConnectionFactoryCreator:205

```
final RabbitAdmin rabbitAdmin = newRabbitAdmin(connectionFactory);
```

MultiRabbitListenerAnnotationBeanPostProcessor:48 
```
final Collection<Declarable> declarables = super.processAmqpListener(rabbitListenerRef, method, bean, beanName);
```
